language: python3
python:
  - "3.6"
sudo: required
dist: trusty
install:
  - gem install rake
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy=1.12.*
  - pandas=0.19.*
  - scipy=0.19.*
  - scikit-learn=0.18.*
  - openmpi=2.1.1
  - networkx=1.11
  - xgboost=0.6a2
  - lightgbm=2.0.4
install:
  - pip3.6 install -r requirements.txt
script: 
  - pytest
