language: python3
virtualenv:
  system_site_packages: true
before_install:
  - pyenv global system 3.6
install:
  - sudo apt-get install python3-pip
  - sudo pip3 install -r requirements.txt
script: 
  - pytest
