language: python3
sudo: required
before_install:
  - pyenv global system 3.6
  - pip3 install virtualenv
  - python3 -m venv venv 
  - source venv/bin/activate
  - pip3 install jupyter pyyaml hyperopt scikit-optimize pandas networkx==1.11    
install:
  - gem install rake
  - pip install --upgrade setuptools
  - git clone --recursive https://github.com/Microsoft/LightGBM
  - cd LightGBM
  - git checkout 80c641cd17727bebea613af3cbfe3b985dbd3313
  - mkdir build && cd build && cmake -DUSE_MPI=ON ..
  - make -j
  - cd ../python-package/ && python3 setup.py install
  - cd ../../
  - rm -rf LightGBM

  - git clone --recursive https://github.com/dmlc/xgboost
  - cd xgboost
  - git checkout 14fba01b5ac42506741e702d3fde68344a82f9f0
  - make -j
  - cd python-package; python3 setup.py install
  - cd ../../
  - rm -rf xgboost
script: 
  - pytest
