sudo: required

language: python

services:
  - docker

before_install:
  - git clone https://github.com/yandexdataschool/modelgym.git
  - cd ./modelgym
  - docker pull modelgym/dockers 
  - docker run -ti --rm  -v "$(pwd)":/src  -p 7777:8888    modelgym/dockers:latest  bash --login

script:
  - pytest
